name: "VPROFILE IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3 # Specify version

      - name: "Setup Terraform in runner"
        uses: hashicorp/setup-terraform@v2.1.0 # Specify version

      - name: "Init Terraform in runner"
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: "Format Terraform in runner"
        id: fmt
        run: terraform fmt -check

      - name: "Validate Terraform in runner"
        id: validate
        run: terraform validate

      - name: "Plan Terraform in runner"
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: "Terraform plan status"
        if: steps.plan.outcome == 'failure'
        run: "exit 1"

      - name: "Apply Terraform."
        id: apply
        run: terraform apply

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1
  EKS_CLUSTER: sergiod3v-eks
